spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=1000
    url: jdbc:p6spy:h2:mem:test;DB_CLOSE_DELAY=1000
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  sql:
    init:
      schema-locations: classpath*:schema.sql